-- colors.lua
--------------------------------------------------------------------------------
-- COLOR PALETTE (Material You / Matugen)
--------------------------------------------------------------------------------

local colors = {
    wallpaper                  = "/home/plagus/Pictures/wallpapers/Castle.jpg",
    background                 = "rgba(0e1415ff)",
    error                      = "rgba(ffb4abff)",
    error_container            = "rgba(93000aff)",
    inverse_on_surface         = "rgba(2b3232ff)",
    inverse_primary            = "rgba(00696bff)",
    inverse_surface            = "rgba(dde4e3ff)",
    on_background              = "rgba(dde4e3ff)",
    on_error                   = "rgba(690005ff)",
    on_error_container         = "rgba(ffdad6ff)",
    on_primary                 = "rgba(003738ff)",
    on_primary_container       = "rgba(9cf1f2ff)",
    on_primary_fixed           = "rgba(002020ff)",
    on_primary_fixed_variant   = "rgba(004f51ff)",
    on_secondary               = "rgba(1b3435ff)",
    on_secondary_container     = "rgba(cce8e8ff)",
    on_secondary_fixed         = "rgba(041f20ff)",
    on_secondary_fixed_variant = "rgba(324b4bff)",
    on_surface                 = "rgba(dde4e3ff)",
    on_surface_variant         = "rgba(bec8c8ff)",
    on_tertiary                = "rgba(1d314cff)",
    on_tertiary_container      = "rgba(d4e3ffff)",
    on_tertiary_fixed          = "rgba(051c35ff)",
    on_tertiary_fixed_variant  = "rgba(344863ff)",
    outline                    = "rgba(899392ff)",
    outline_variant            = "rgba(3f4949ff)",
    primary                    = "rgba(80d4d6ff)",
    primary_container          = "rgba(004f51ff)",
    primary_fixed              = "rgba(9cf1f2ff)",
    primary_fixed_dim          = "rgba(80d4d6ff)",
    scrim                      = "rgba(000000ff)",
    secondary                  = "rgba(b0ccccff)",
    secondary_container        = "rgba(324b4bff)",
    secondary_fixed            = "rgba(cce8e8ff)",
    secondary_fixed_dim        = "rgba(b0ccccff)",
    shadow                     = "rgba(000000ff)",
    source_color               = "rgba(131818ff)",
    surface                    = "rgba(0e1415ff)",
    surface_bright             = "rgba(343a3aff)",
    surface_container          = "rgba(1a2121ff)",
    surface_container_high     = "rgba(252b2bff)",
    surface_container_highest  = "rgba(2f3636ff)",
    surface_container_low      = "rgba(161d1dff)",
    surface_container_lowest   = "rgba(090f0fff)",
    surface_dim                = "rgba(0e1415ff)",
    surface_tint               = "rgba(80d4d6ff)",
    surface_variant            = "rgba(3f4949ff)",
    tertiary                   = "rgba(b4c8e9ff)",
    tertiary_container         = "rgba(344863ff)",
    tertiary_fixed             = "rgba(d4e3ffff)",
    tertiary_fixed_dim         = "rgba(b4c8e9ff)",
}

-- Expose to Hyprland config
hl.config({
    $image = colors.wallpaper,
    $background = colors.background,
    $error = colors.error,
    $error_container = colors.error_container,
    $inverse_on_surface = colors.inverse_on_surface,
    $inverse_primary = colors.inverse_primary,
    $inverse_surface = colors.inverse_surface,
    $on_background = colors.on_background,
    $on_error = colors.on_error,
    $on_error_container = colors.on_error_container,
    $on_primary = colors.on_primary,
    $on_primary_container = colors.on_primary_container,
    $on_primary_fixed = colors.on_primary_fixed,
    $on_primary_fixed_variant = colors.on_primary_fixed_variant,
    $on_secondary = colors.on_secondary,
    $on_secondary_container = colors.on_secondary_container,
    $on_secondary_fixed = colors.on_secondary_fixed,
    $on_secondary_fixed_variant = colors.on_secondary_fixed_variant,
    $on_surface = colors.on_surface,
    $on_surface_variant = colors.on_surface_variant,
    $on_tertiary = colors.on_tertiary,
    $on_tertiary_container = colors.on_tertiary_container,
    $on_tertiary_fixed = colors.on_tertiary_fixed,
    $on_tertiary_fixed_variant = colors.on_tertiary_fixed_variant,
    $outline = colors.outline,
    $outline_variant = colors.outline_variant,
    $primary = colors.primary,
    $primary_container = colors.primary_container,
    $primary_fixed = colors.primary_fixed,
    $primary_fixed_dim = colors.primary_fixed_dim,
    $scrim = colors.scrim,
    $secondary = colors.secondary,
    $secondary_container = colors.secondary_container,
    $secondary_fixed = colors.secondary_fixed,
    $secondary_fixed_dim = colors.secondary_fixed_dim,
    $shadow = colors.shadow,
    $source_color = colors.source_color,
    $surface = colors.surface,
    $surface_bright = colors.surface_bright,
    $surface_container = colors.surface_container,
    $surface_container_high = colors.surface_container_high,
    $surface_container_highest = colors.surface_container_highest,
    $surface_container_low = colors.surface_container_low,
    $surface_container_lowest = colors.surface_container_lowest,
    $surface_dim = colors.surface_dim,
    $surface_tint = colors.surface_tint,
    $surface_variant = colors.surface_variant,
    $tertiary = colors.tertiary,
    $tertiary_container = colors.tertiary_container,
    $tertiary_fixed = colors.tertiary_fixed,
    $tertiary_fixed_dim = colors.tertiary_fixed_dim,
})

return colors