-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: bind.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("bind")
-- Source: animation.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("animation")
-- Source: looknfeel.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("looknfeel")
-- Source: permissions.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("permissions")
-- Source: startup.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("startup")
-- Source: env.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("env")
-- Source: input.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("input")
-- Source: colors.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("colors")

--###############
--## MONITORS ###
--###############

-- See https://wiki.hyprland.org/Configuring/Monitors/
--
-- HDMI is now at the top-left (0,0)
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60",
    position = "0x0",
    scale = "1",
})

hl.monitor({
    output = "VGA-1",
    mode = "1680x1050@60",
    position = "3840x0",
    scale = "1",
})

-- Laptop screen is moved to the right (starts at 1920)
hl.monitor({
    output = "eDP-1",
    mode = "1920x1200@60",
    position = "1920x0",
    scale = "1.25",
})

-- Top and bottom 
-- monitor=HDMI-A-1,1920x1080@60,0x0,1
-- monitor=eDP-1,1920x1200@60,0x1080,1

--
-- monitor=HDMI-A-1,1920x1080@60,0x0,1,mirror, eDP-1
-- monitor=eDP-1,1920x1080@60,1920x0,1

hl.workspace_rule({
    workspace = "1",
    monitor = "HDMI-A-1",
})

hl.workspace_rule({
    workspace = "2",
    monitor = "HDMI-A-1",
})

hl.workspace_rule({
    workspace = "3",
    monitor = "HDMI-A-1",
})

hl.workspace_rule({
    workspace = "4",
    monitor = "HDMI-A-1",
})

hl.workspace_rule({
    workspace = "5",
    monitor = "HDMI-A-1",
})

hl.workspace_rule({
    workspace = "6",
    monitor = "eDP-1",
})

--#############################
--## WINDOWS AND WORKSPACES ###
--#############################

-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
-- See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

-- Example windowrule
-- windowrule = float,class:^(kitty)$,title:^(kitty)$

-- Ignore maximize requests from apps. You'll probably like this.
-- windowrule = suppressevent=maximize class=.*

-- Fix some dragging issues with XWayland
--windowrule = nofocus=1 class=^$ title=^$ xwayland=1 floating=1 fullscreen=0 pinned=0

--##############
--## PLUGINS ###
--##############

-- TODO: manual review — plugin section ''. The new Lua API exposes plugins via hl.plugin.<name>(...) — wire up per the plugin's docs.
--[[
  hyprexpo { ... }
]]

--[[
hl.config({
    plugin = {
        hyprexpo = {
            columns = 2,
            gap_size = 5,
            bg_col = "rgb(111111)",
            workspace_method = "center 1",
            skip_empty = true,
            -- gesture_distance = 300,
        },
    },
})
HYPREXPO ISN'T MAINTAINED ANYMORE
]]

