--################
--## AUTOSTART ###
--################

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:

-- exec-once = $terminal
-- exec-once = firefox
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

--exec-once = hyprlock

hl.on("hyprland.start", function()
    hl.exec_cmd("hyprpm reload -n")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("swaync")
    hl.exec_cmd("wl-paste --watch cliphist store &")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("otd-daemon")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("~/.config/waybar/scripts/theme-switcher.sh restore")
    hl.exec_cmd("waybar")
    hl.exec_cmd("blueman-applet")
    hl.exec_cmd("wl-paste --watch cliphist store")
end)

